# What follows was GENERATED by mkwasmbuilds.c. Edit at your own risk.

########################################################################
# Build setup sanity checks...
ifeq (,$(dir.top))
  $(error build process error: expecting make var $$(dir.top) to have been set up by now)
endif
ifeq (,$(dir.api))
  $(error build process error: expecting make var $$(dir.api) to have been set up by now)
endif
ifeq (,$(dir.dout))
  $(error build process error: expecting make var $$(dir.dout) to have been set up by now)
endif
ifeq (,$(dir.tmp))
  $(error build process error: expecting make var $$(dir.tmp) to have been set up by now)
endif
ifeq (,$(dir.fiddle))
  $(error build process error: expecting make var $$(dir.fiddle) to have been set up by now)
endif
ifeq (,$(dir.fiddle.debug))
  $(error build process error: expecting make var $$(dir.fiddle.debug) to have been set up by now)
endif
define label.unsupported-build
$(emo.fire)$(emo.fire)$(emo.fire)Unsupported build: use at your own risk!
endef

########################################################################
b.call.wasm-strip = echo '[$(emo.b.$(1)) $(out.$(1).wasm)] $(emo.strip) wasm-strip'; $(bin.wasm-strip) $(out.$(1).wasm)


########################################################################
define b.do.emcc
$(bin.emcc) -o $@ $(emcc_opt_full) $(emcc.flags) $(emcc.jsflags) -sENVIRONMENT=$(emcc.environment.$(1))  $(pre-post.$(1).flags)  $(emcc.flags.$(1))  $(cflags.common) $(cflags.$(1))  $(SQLITE_OPT)  $(cflags.wasm_extra_init) $(sqlite3-wasm.c.in)
endef

########################################################################
# post-compilation WASM file optimization
ifeq (,$(bin.wasm-opt))
b.do.wasm-opt = echo '$(logtag.$(1)) wasm-opt not available'
else
define b.do.wasm-opt
echo '[$(emo.b.$(1)) $(out.$(1).wasm)] $(emo.wasm-opt) $(bin.wasm-opt)';\
	tmpfile=$(dir.dout.$(1))/wasm-opt-tmp.$(1).wasm; \
	rm -f $$tmpfile; \
	if $(bin.wasm-opt) $(out.$(1).wasm) -o $$tmpfile \
		--all-features --post-emscripten --strip-debug --local-cse ; then \
		mv $$tmpfile $(out.$(1).wasm); \
	else \
		rm -f $$tmpfile; \
		echo '$(logtag.$(1)) $(emo.fire) ignoring wasm-opt failure'; \
	fi
endef
endif
more: all

########################################################################
# Begin build [🍦vanilla]. flags=0xc0000000
# zCmppD=
# zBaseName=sqlite3
b.names += vanilla
emo.b.vanilla = 🍦
logtag.vanilla ?= [$(emo.b.vanilla)$(if $@, $@,)]:
$(info $(logtag.vanilla) Setting up target b-vanilla)
dir.dout.vanilla ?= $(dir.dout)/vanilla
out.vanilla.base ?= $(dir.dout.vanilla)/sqlite3
out.vanilla.js ?= $(dir.dout.vanilla)/sqlite3.js
out.vanilla.wasm ?= $(dir.dout.vanilla)/sqlite3.wasm
dir.dout.vanilla ?= $(dir.dout)/vanilla
c-pp.D.vanilla ?= 
emcc.environment.vanilla ?= web,worker
sqlite3-api.vanilla.js = $(dir.tmp)/sqlite3-api.vanilla.js
$(eval $(call b.c-pp.target,vanilla,$(sqlite3-api.jses),$(sqlite3-api.vanilla.js),$(c-pp.D.vanilla)))
$(out.vanilla.js): $(sqlite3-api.vanilla.js)
$(sqlite3-api.vanilla.js): $(dir.api)/opfs-common-shared.c-pp.js $(dir.api)/opfs-common-inline.c-pp.js

########################################################################
# Begin --pre/--post flags for vanilla
# --pre-js=...
pre-js.vanilla.js = $(dir.tmp)/pre-js.vanilla.js
$(pre-js.vanilla.js): $(pre-js.in.js) $(bin.c-pp) $(MAKEFILE_LIST)
	@$(call b.mkdir@); $(call b.c-pp.shcmd,vanilla,$(pre-js.in.js),$(pre-js.vanilla.js),$(c-pp.D.vanilla) -DModule.instantiateWasm )

# --post-js=...
post-js.vanilla.js = $(dir.tmp)/post-js.vanilla.js
post-js.vanilla.in = $(dir.api)/post-js-header.js $(sqlite3-api.vanilla.js) $(dir.api)/post-js-footer.js
$(eval $(call b.c-pp.target,vanilla,$(post-js.vanilla.in),$(post-js.vanilla.js),$(c-pp.D.vanilla)))
$(post-js.vanilla.js): $(post-js.vanilla.in) $(bin.c-pp)

# --extern-post-js=...
extern-post-js.vanilla.js = $(dir.tmp)/extern-post-js.vanilla.js
$(eval $(call b.c-pp.target,vanilla,$(extern-post-js.in.js),$(extern-post-js.vanilla.js),$(c-pp.D.vanilla) --@policy=error -Dsqlite3.wasm=sqlite3.wasm))
# --pre/post misc...
pre-post.vanilla.flags = --extern-pre-js=$(sqlite3-license-version.js) --pre-js=$(pre-js.vanilla.js) --post-js=$(post-js.vanilla.js) --extern-post-js=$(extern-post-js.vanilla.js)
pre-post.vanilla.deps = $(pre-post-jses.common.deps) $(post-js.vanilla.js) $(extern-post-js.vanilla.js) $(dir.tmp)/pre-js.vanilla.js
# End --pre/--post flags for vanilla
########################################################################

########################################################################
$(out.vanilla.js): $(MAKEFILE_LIST) $(sqlite3-wasm.c.in) $(EXPORTED_FUNCTIONS.api) $(deps.vanilla) $(bin.mkwb) $(pre-post.vanilla.deps)
	@$(call b.mkdir@); $(call b.echo,vanilla,$(emo.compile) building ...)
	$(b.cmd@)$(bin.emcc) -o $@ $(emcc_opt_full) $(emcc.flags) $(emcc.jsflags) -sENVIRONMENT=$(emcc.environment.vanilla) $(pre-post.vanilla.flags) $(emcc.flags.vanilla) $(cflags.common) $(cflags.vanilla) $(SQLITE_OPT) $(cflags.wasm_extra_init) $(sqlite3-wasm.c.in)
	@if grep -e '^ *importScripts(' $@; then echo '$(logtag.vanilla) $(emo.bug)$(emo.fire): bug fixed in 65798c09a00662a3 has re-appeared'; exit 1; fi;
	@chmod -x $(out.vanilla.wasm)
	@$(call b.call.wasm-strip,vanilla)
	@$(call b.do.wasm-opt,vanilla)
	@$(call b.strip-js-emcc-bindings,$(logtag.vanilla))
	@$(call b.cp,vanilla,$@,$(dir.dout))
	@$(call b.cp,vanilla,$(basename $@).wasm,$(dir.dout))
	@$(call b.echo,vanilla,$(emo.done) done!)

32bit: $(out.vanilla.js)
$(out.vanilla.wasm): $(out.vanilla.js)
b-vanilla: $(out.vanilla.wasm)
$(dir.dout)/sqlite3.js: $(out.vanilla.js)
$(dir.dout)/sqlite3.wasm: $(out.vanilla.wasm)
all: $(out.vanilla.js)
# End build [vanilla]
########################################################################

########################################################################
# Begin build [🍨vanilla64]. flags=0xc0000018
# zCmppD=
# zBaseName=sqlite3-64bit
b.names += vanilla64
emo.b.vanilla64 = 🍨
logtag.vanilla64 ?= [$(emo.b.vanilla64)$(if $@, $@,)]:
$(info $(logtag.vanilla64) Setting up target b-vanilla64)
dir.dout.vanilla64 ?= $(dir.dout)/vanilla64
out.vanilla64.base ?= $(dir.dout.vanilla64)/sqlite3-64bit
out.vanilla64.js ?= $(dir.dout.vanilla64)/sqlite3-64bit.js
out.vanilla64.wasm ?= $(dir.dout.vanilla64)/sqlite3-64bit.wasm
dir.dout.vanilla64 ?= $(dir.dout)/vanilla64
c-pp.D.vanilla64 ?= 
c-pp.D.vanilla64 += $(c-pp.D.64bit)
emcc.environment.vanilla64 ?= web,worker
emcc.flags.vanilla64 = -sMEMORY64=1 -sWASM_BIGINT=1
sqlite3-api.vanilla64.js = $(dir.tmp)/sqlite3-api.vanilla64.js
$(eval $(call b.c-pp.target,vanilla64,$(sqlite3-api.jses),$(sqlite3-api.vanilla64.js),$(c-pp.D.vanilla64)))
$(out.vanilla64.js): $(sqlite3-api.vanilla64.js)
$(sqlite3-api.vanilla64.js): $(dir.api)/opfs-common-shared.c-pp.js $(dir.api)/opfs-common-inline.c-pp.js

########################################################################
# Begin --pre/--post flags for vanilla64
# --pre-js=...
pre-js.vanilla64.js = $(dir.tmp)/pre-js.vanilla64.js
$(pre-js.vanilla64.js): $(pre-js.in.js) $(bin.c-pp) $(MAKEFILE_LIST)
	@$(call b.mkdir@); $(call b.c-pp.shcmd,vanilla64,$(pre-js.in.js),$(pre-js.vanilla64.js),$(c-pp.D.vanilla64) -DModule.instantiateWasm )

# --post-js=...
post-js.vanilla64.js = $(dir.tmp)/post-js.vanilla64.js
post-js.vanilla64.in = $(dir.api)/post-js-header.js $(sqlite3-api.vanilla64.js) $(dir.api)/post-js-footer.js
$(eval $(call b.c-pp.target,vanilla64,$(post-js.vanilla64.in),$(post-js.vanilla64.js),$(c-pp.D.vanilla64)))
$(post-js.vanilla64.js): $(post-js.vanilla64.in) $(bin.c-pp)

# --extern-post-js=...
extern-post-js.vanilla64.js = $(dir.tmp)/extern-post-js.vanilla64.js
$(eval $(call b.c-pp.target,vanilla64,$(extern-post-js.in.js),$(extern-post-js.vanilla64.js),$(c-pp.D.vanilla64) --@policy=error -Dsqlite3.wasm=sqlite3-64bit.wasm))
# --pre/post misc...
pre-post.vanilla64.flags = --extern-pre-js=$(sqlite3-license-version.js) --pre-js=$(pre-js.vanilla64.js) --post-js=$(post-js.vanilla64.js) --extern-post-js=$(extern-post-js.vanilla64.js)
pre-post.vanilla64.deps = $(pre-post-jses.common.deps) $(post-js.vanilla64.js) $(extern-post-js.vanilla64.js) $(dir.tmp)/pre-js.vanilla64.js
# End --pre/--post flags for vanilla64
########################################################################

########################################################################
$(out.vanilla64.js): $(MAKEFILE_LIST) $(sqlite3-wasm.c.in) $(EXPORTED_FUNCTIONS.api) $(deps.vanilla64) $(bin.mkwb) $(pre-post.vanilla64.deps)
	@$(call b.mkdir@); $(call b.echo,vanilla64,$(emo.compile) building ...)
	$(b.cmd@)$(bin.emcc) -o $@ $(emcc_opt_full) $(emcc.flags) $(emcc.jsflags) -sENVIRONMENT=$(emcc.environment.vanilla64) $(pre-post.vanilla64.flags) $(emcc.flags.vanilla64) $(cflags.common) $(cflags.vanilla64) $(SQLITE_OPT) $(cflags.wasm_extra_init) $(sqlite3-wasm.c.in)
	@if grep -e '^ *importScripts(' $@; then echo '$(logtag.vanilla64) $(emo.bug)$(emo.fire): bug fixed in 65798c09a00662a3 has re-appeared'; exit 1; fi;
	@chmod -x $(out.vanilla64.wasm)
	@$(call b.call.wasm-strip,vanilla64)
	@$(call b.do.wasm-opt,vanilla64)
	@$(call b.strip-js-emcc-bindings,$(logtag.vanilla64))
	@$(call b.cp,vanilla64,$@,$(dir.dout))
	@$(call b.cp,vanilla64,$(basename $@).wasm,$(dir.dout))
	@$(call b.echo,vanilla64,$(emo.done) done!)

64bit: $(out.vanilla64.js)
$(out.vanilla64.wasm): $(out.vanilla64.js)
b-vanilla64: $(out.vanilla64.wasm)
$(dir.dout)/sqlite3-64bit.js: $(out.vanilla64.js)
$(dir.dout)/sqlite3-64bit.wasm: $(out.vanilla64.wasm)
more: $(out.vanilla64.js)
# End build [vanilla64]
########################################################################

########################################################################
# Begin build [🍬esm]. flags=0x40000001
# zCmppD=-Dtarget:es6-module
# zBaseName=sqlite3
b.names += esm
emo.b.esm = 🍬
logtag.esm ?= [$(emo.b.esm)$(if $@, $@,)]:
$(info $(logtag.esm) Setting up target b-esm)
dir.dout.esm ?= $(dir.dout)/esm
out.esm.base ?= $(dir.dout.esm)/sqlite3
out.esm.js ?= $(dir.dout.esm)/sqlite3.mjs
out.esm.wasm ?= $(dir.dout.esm)/sqlite3.wasm
dir.dout.esm ?= $(dir.dout)/esm
c-pp.D.esm ?= -Dtarget:es6-module
emcc.environment.esm ?= web,worker
sqlite3-api.esm.js = $(dir.tmp)/sqlite3-api.esm.js
$(eval $(call b.c-pp.target,esm,$(sqlite3-api.jses),$(sqlite3-api.esm.js),$(c-pp.D.esm)))
$(out.esm.js): $(sqlite3-api.esm.js)
$(sqlite3-api.esm.js): $(dir.api)/opfs-common-shared.c-pp.js $(dir.api)/opfs-common-inline.c-pp.js

########################################################################
# Begin --pre/--post flags for esm
# --pre-js=...
pre-js.esm.js = $(dir.tmp)/pre-js.esm.js
$(pre-js.esm.js): $(pre-js.in.js) $(bin.c-pp) $(MAKEFILE_LIST)
	@$(call b.mkdir@); $(call b.c-pp.shcmd,esm,$(pre-js.in.js),$(pre-js.esm.js),$(c-pp.D.esm) -DModule.instantiateWasm )

# --post-js=...
post-js.esm.js = $(dir.tmp)/post-js.esm.js
post-js.esm.in = $(dir.api)/post-js-header.js $(sqlite3-api.esm.js) $(dir.api)/post-js-footer.js
$(eval $(call b.c-pp.target,esm,$(post-js.esm.in),$(post-js.esm.js),$(c-pp.D.esm)))
$(post-js.esm.js): $(post-js.esm.in) $(bin.c-pp)

# --extern-post-js=...
extern-post-js.esm.js = $(dir.tmp)/extern-post-js.esm.js
$(eval $(call b.c-pp.target,esm,$(extern-post-js.in.js),$(extern-post-js.esm.js),$(c-pp.D.esm) --@policy=error -Dsqlite3.wasm=sqlite3.wasm))
# --pre/post misc...
pre-post.esm.flags = --extern-pre-js=$(sqlite3-license-version.js) --pre-js=$(pre-js.esm.js) --post-js=$(post-js.esm.js) --extern-post-js=$(extern-post-js.esm.js)
pre-post.esm.deps = $(pre-post-jses.common.deps) $(post-js.esm.js) $(extern-post-js.esm.js) $(dir.tmp)/pre-js.esm.js
# End --pre/--post flags for esm
########################################################################

########################################################################
$(out.esm.js): $(MAKEFILE_LIST) $(sqlite3-wasm.c.in) $(EXPORTED_FUNCTIONS.api) $(deps.esm) $(bin.mkwb) $(pre-post.esm.deps)
	@$(call b.mkdir@); $(call b.echo,esm,$(emo.compile) building ...)
	$(b.cmd@)$(bin.emcc) -o $@ $(emcc_opt_full) $(emcc.flags) $(emcc.jsflags) -sENVIRONMENT=$(emcc.environment.esm) $(pre-post.esm.flags) $(emcc.flags.esm) $(cflags.common) $(cflags.esm) $(SQLITE_OPT) $(cflags.wasm_extra_init) $(sqlite3-wasm.c.in)
	@if grep -e '^ *importScripts(' $@; then echo '$(logtag.esm) $(emo.bug)$(emo.fire): bug fixed in 65798c09a00662a3 has re-appeared'; exit 1; fi;
	@$(call b.call.patch-export-default,1,0,$(logtag.esm))
	@chmod -x $(out.esm.wasm)
	@$(call b.call.wasm-strip,esm)
	@$(call b.do.wasm-opt,esm)
	@$(call b.strip-js-emcc-bindings,$(logtag.esm))
	@$(call b.cp,esm,$@,$(dir.dout))
	@$(call b.echo,esm,$(emo.done) done!)

32bit: $(out.esm.js)
$(out.esm.wasm): $(out.esm.js)
b-esm: $(out.esm.wasm)
$(dir.dout)/sqlite3.mjs: $(out.esm.js)
all: $(out.esm.js)
# End build [esm]
########################################################################

########################################################################
# Begin build [🍫esm64]. flags=0x40000019
# zCmppD=-Dtarget:es6-module
# zBaseName=sqlite3-64bit
b.names += esm64
emo.b.esm64 = 🍫
logtag.esm64 ?= [$(emo.b.esm64)$(if $@, $@,)]:
$(info $(logtag.esm64) Setting up target b-esm64)
dir.dout.esm64 ?= $(dir.dout)/esm64
out.esm64.base ?= $(dir.dout.esm64)/sqlite3-64bit
out.esm64.js ?= $(dir.dout.esm64)/sqlite3-64bit.mjs
out.esm64.wasm ?= $(dir.dout.esm64)/sqlite3-64bit.wasm
dir.dout.esm64 ?= $(dir.dout)/esm64
c-pp.D.esm64 ?= -Dtarget:es6-module
c-pp.D.esm64 += $(c-pp.D.64bit)
emcc.environment.esm64 ?= web,worker
emcc.flags.esm64 = -sMEMORY64=1 -sWASM_BIGINT=1
sqlite3-api.esm64.js = $(dir.tmp)/sqlite3-api.esm64.js
$(eval $(call b.c-pp.target,esm64,$(sqlite3-api.jses),$(sqlite3-api.esm64.js),$(c-pp.D.esm64)))
$(out.esm64.js): $(sqlite3-api.esm64.js)
$(sqlite3-api.esm64.js): $(dir.api)/opfs-common-shared.c-pp.js $(dir.api)/opfs-common-inline.c-pp.js

########################################################################
# Begin --pre/--post flags for esm64
# --pre-js=...
pre-js.esm64.js = $(dir.tmp)/pre-js.esm64.js
$(pre-js.esm64.js): $(pre-js.in.js) $(bin.c-pp) $(MAKEFILE_LIST)
	@$(call b.mkdir@); $(call b.c-pp.shcmd,esm64,$(pre-js.in.js),$(pre-js.esm64.js),$(c-pp.D.esm64) -DModule.instantiateWasm )

# --post-js=...
post-js.esm64.js = $(dir.tmp)/post-js.esm64.js
post-js.esm64.in = $(dir.api)/post-js-header.js $(sqlite3-api.esm64.js) $(dir.api)/post-js-footer.js
$(eval $(call b.c-pp.target,esm64,$(post-js.esm64.in),$(post-js.esm64.js),$(c-pp.D.esm64)))
$(post-js.esm64.js): $(post-js.esm64.in) $(bin.c-pp)

# --extern-post-js=...
extern-post-js.esm64.js = $(dir.tmp)/extern-post-js.esm64.js
$(eval $(call b.c-pp.target,esm64,$(extern-post-js.in.js),$(extern-post-js.esm64.js),$(c-pp.D.esm64) --@policy=error -Dsqlite3.wasm=sqlite3-64bit.wasm))
# --pre/post misc...
pre-post.esm64.flags = --extern-pre-js=$(sqlite3-license-version.js) --pre-js=$(pre-js.esm64.js) --post-js=$(post-js.esm64.js) --extern-post-js=$(extern-post-js.esm64.js)
pre-post.esm64.deps = $(pre-post-jses.common.deps) $(post-js.esm64.js) $(extern-post-js.esm64.js) $(dir.tmp)/pre-js.esm64.js
# End --pre/--post flags for esm64
########################################################################

########################################################################
$(out.esm64.js): $(MAKEFILE_LIST) $(sqlite3-wasm.c.in) $(EXPORTED_FUNCTIONS.api) $(deps.esm64) $(bin.mkwb) $(pre-post.esm64.deps)
	@$(call b.mkdir@); $(call b.echo,esm64,$(emo.compile) building ...)
	$(b.cmd@)$(bin.emcc) -o $@ $(emcc_opt_full) $(emcc.flags) $(emcc.jsflags) -sENVIRONMENT=$(emcc.environment.esm64) $(pre-post.esm64.flags) $(emcc.flags.esm64) $(cflags.common) $(cflags.esm64) $(SQLITE_OPT) $(cflags.wasm_extra_init) $(sqlite3-wasm.c.in)
	@if grep -e '^ *importScripts(' $@; then echo '$(logtag.esm64) $(emo.bug)$(emo.fire): bug fixed in 65798c09a00662a3 has re-appeared'; exit 1; fi;
	@$(call b.call.patch-export-default,1,0,$(logtag.esm64))
	@chmod -x $(out.esm64.wasm)
	@$(call b.call.wasm-strip,esm64)
	@$(call b.do.wasm-opt,esm64)
	@$(call b.strip-js-emcc-bindings,$(logtag.esm64))
	@$(call b.cp,esm64,$@,$(dir.dout))
	@$(call b.echo,esm64,$(emo.done) done!)

64bit: $(out.esm64.js)
$(out.esm64.wasm): $(out.esm64.js)
b-esm64: $(out.esm64.wasm)
$(dir.dout)/sqlite3-64bit.mjs: $(out.esm64.js)
more: $(out.esm64.js)
# End build [esm64]
########################################################################

########################################################################
# Begin build [👛bundler]. flags=0x4000000b
# zCmppD=$(c-pp.D.esm) -Dtarget:es6-bundler-friendly
# zBaseName=sqlite3-bundler-friendly
b.names += bundler
emo.b.bundler = 👛
logtag.bundler ?= [$(emo.b.bundler)$(if $@, $@,)]:
$(info $(logtag.bundler) Setting up target b-bundler)
dir.dout.bundler ?= $(dir.dout)/bundler
out.bundler.base ?= $(dir.dout.bundler)/sqlite3-bundler-friendly
out.bundler.js ?= $(dir.dout.bundler)/sqlite3-bundler-friendly.mjs
out.bundler.wasm ?= $(dir.dout.bundler)/sqlite3-bundler-friendly.wasm
dir.dout.bundler ?= $(dir.dout)/bundler
c-pp.D.bundler ?= $(c-pp.D.esm) -Dtarget:es6-bundler-friendly
emcc.environment.bundler ?= web,worker
sqlite3-api.bundler.js = $(dir.tmp)/sqlite3-api.bundler.js
$(eval $(call b.c-pp.target,bundler,$(sqlite3-api.jses),$(sqlite3-api.bundler.js),$(c-pp.D.bundler)))
$(out.bundler.js): $(sqlite3-api.bundler.js)
$(sqlite3-api.bundler.js): $(dir.api)/opfs-common-shared.c-pp.js $(dir.api)/opfs-common-inline.c-pp.js

########################################################################
# Begin --pre/--post flags for bundler
# --pre-js=...
pre-js.bundler.js = $(dir.tmp)/pre-js.bundler.js
$(pre-js.bundler.js): $(pre-js.in.js) $(bin.c-pp) $(MAKEFILE_LIST) $(dir.dout)/sqlite3.wasm
	@$(call b.mkdir@); $(call b.c-pp.shcmd,bundler,$(pre-js.in.js),$(pre-js.bundler.js),$(c-pp.D.bundler) -DModule.instantiateWasm )

# --post-js=...
post-js.bundler.js = $(dir.tmp)/post-js.bundler.js
post-js.bundler.in = $(dir.api)/post-js-header.js $(sqlite3-api.bundler.js) $(dir.api)/post-js-footer.js
$(eval $(call b.c-pp.target,bundler,$(post-js.bundler.in),$(post-js.bundler.js),$(c-pp.D.bundler)))
$(post-js.bundler.js): $(post-js.bundler.in) $(bin.c-pp)

# --extern-post-js=...
extern-post-js.bundler.js = $(dir.tmp)/extern-post-js.bundler.js
$(eval $(call b.c-pp.target,bundler,$(extern-post-js.in.js),$(extern-post-js.bundler.js),$(c-pp.D.bundler) --@policy=error -Dsqlite3.wasm=sqlite3-bundler-friendly.wasm))
# --pre/post misc...
pre-post.bundler.flags = --extern-pre-js=$(sqlite3-license-version.js) --pre-js=$(pre-js.bundler.js) --post-js=$(post-js.bundler.js) --extern-post-js=$(extern-post-js.bundler.js)
pre-post.bundler.deps = $(pre-post-jses.common.deps) $(post-js.bundler.js) $(extern-post-js.bundler.js) $(dir.tmp)/pre-js.bundler.js
# End --pre/--post flags for bundler
########################################################################

########################################################################
$(out.bundler.js): $(MAKEFILE_LIST) $(sqlite3-wasm.c.in) $(EXPORTED_FUNCTIONS.api) $(deps.bundler) $(bin.mkwb) $(pre-post.bundler.deps)
	@$(call b.mkdir@); $(call b.echo,bundler,$(emo.compile) building ...)
	$(b.cmd@)$(bin.emcc) -o $@ $(emcc_opt_full) $(emcc.flags) $(emcc.jsflags) -sENVIRONMENT=$(emcc.environment.bundler) $(pre-post.bundler.flags) $(emcc.flags.bundler) $(cflags.common) $(cflags.bundler) $(SQLITE_OPT) $(cflags.wasm_extra_init) $(sqlite3-wasm.c.in)
	@if grep -e '^ *importScripts(' $@; then echo '$(logtag.bundler) $(emo.bug)$(emo.fire): bug fixed in 65798c09a00662a3 has re-appeared'; exit 1; fi;
	@$(call b.call.patch-export-default,1,0,$(logtag.bundler))
	@chmod -x $(out.bundler.wasm)
	@$(call b.call.wasm-strip,bundler)
	@$(call b.do.wasm-opt,bundler)
	@$(call b.strip-js-emcc-bindings,$(logtag.bundler))
	@echo '$(logtag.bundler) $(emo.disk) s/"sqlite3-bundler-friendly.wasm"/"sqlite3.wasm"/g in $(dir.dout)/$(notdir $@)'; \
sed -e 's/"sqlite3-bundler-friendly.wasm"/"sqlite3.wasm"/g' -e "s/'sqlite3-bundler-friendly.wasm'/'sqlite3.wasm'/g" $@ > $(dir.dout)/$(notdir $@);
	@$(call b.echo,bundler,$(emo.done) done!)

32bit: $(out.bundler.js)
$(out.bundler.wasm): $(out.bundler.js)
b-bundler: $(out.bundler.wasm)
$(dir.dout)/sqlite3-bundler-friendly.mjs: $(out.bundler.js)
more: $(out.bundler.js)
# End build [bundler]
########################################################################

########################################################################
# Begin build [📦bundler64]. flags=0x4000001b
# zCmppD=$(c-pp.D.bundler)
# zBaseName=sqlite3-bundler-friendly-64bit
b.names += bundler64
emo.b.bundler64 = 📦
logtag.bundler64 ?= [$(emo.b.bundler64)$(if $@, $@,)]:
$(info $(logtag.bundler64) Setting up target b-bundler64)
dir.dout.bundler64 ?= $(dir.dout)/bundler64
out.bundler64.base ?= $(dir.dout.bundler64)/sqlite3-bundler-friendly-64bit
out.bundler64.js ?= $(dir.dout.bundler64)/sqlite3-bundler-friendly-64bit.mjs
out.bundler64.wasm ?= $(dir.dout.bundler64)/sqlite3-bundler-friendly-64bit.wasm
dir.dout.bundler64 ?= $(dir.dout)/bundler64
c-pp.D.bundler64 ?= $(c-pp.D.bundler)
c-pp.D.bundler64 += $(c-pp.D.64bit)
emcc.environment.bundler64 ?= web,worker
emcc.flags.bundler64 = -sMEMORY64=1
sqlite3-api.bundler64.js = $(dir.tmp)/sqlite3-api.bundler64.js
$(eval $(call b.c-pp.target,bundler64,$(sqlite3-api.jses),$(sqlite3-api.bundler64.js),$(c-pp.D.bundler64)))
$(out.bundler64.js): $(sqlite3-api.bundler64.js)
$(sqlite3-api.bundler64.js): $(dir.api)/opfs-common-shared.c-pp.js $(dir.api)/opfs-common-inline.c-pp.js

########################################################################
# Begin --pre/--post flags for bundler64
# --pre-js=...
pre-js.bundler64.js = $(dir.tmp)/pre-js.bundler64.js
$(pre-js.bundler64.js): $(pre-js.in.js) $(bin.c-pp) $(MAKEFILE_LIST) $(dir.dout)/sqlite3-64bit.wasm
	@$(call b.mkdir@); $(call b.c-pp.shcmd,bundler64,$(pre-js.in.js),$(pre-js.bundler64.js),$(c-pp.D.bundler64) -DModule.instantiateWasm )

# --post-js=...
post-js.bundler64.js = $(dir.tmp)/post-js.bundler64.js
post-js.bundler64.in = $(dir.api)/post-js-header.js $(sqlite3-api.bundler64.js) $(dir.api)/post-js-footer.js
$(eval $(call b.c-pp.target,bundler64,$(post-js.bundler64.in),$(post-js.bundler64.js),$(c-pp.D.bundler64)))
$(post-js.bundler64.js): $(post-js.bundler64.in) $(bin.c-pp)

# --extern-post-js=...
extern-post-js.bundler64.js = $(dir.tmp)/extern-post-js.bundler64.js
$(eval $(call b.c-pp.target,bundler64,$(extern-post-js.in.js),$(extern-post-js.bundler64.js),$(c-pp.D.bundler64) --@policy=error -Dsqlite3.wasm=sqlite3-bundler-friendly-64bit.wasm))
# --pre/post misc...
pre-post.bundler64.flags = --extern-pre-js=$(sqlite3-license-version.js) --pre-js=$(pre-js.bundler64.js) --post-js=$(post-js.bundler64.js) --extern-post-js=$(extern-post-js.bundler64.js)
pre-post.bundler64.deps = $(pre-post-jses.common.deps) $(post-js.bundler64.js) $(extern-post-js.bundler64.js) $(dir.tmp)/pre-js.bundler64.js
# End --pre/--post flags for bundler64
########################################################################

########################################################################
$(out.bundler64.js): $(MAKEFILE_LIST) $(sqlite3-wasm.c.in) $(EXPORTED_FUNCTIONS.api) $(deps.bundler64) $(bin.mkwb) $(pre-post.bundler64.deps)
	@$(call b.mkdir@); $(call b.echo,bundler64,$(emo.compile) building ...)
	$(b.cmd@)$(bin.emcc) -o $@ $(emcc_opt_full) $(emcc.flags) $(emcc.jsflags) -sENVIRONMENT=$(emcc.environment.bundler64) $(pre-post.bundler64.flags) $(emcc.flags.bundler64) $(cflags.common) $(cflags.bundler64) $(SQLITE_OPT) $(cflags.wasm_extra_init) $(sqlite3-wasm.c.in)
	@if grep -e '^ *importScripts(' $@; then echo '$(logtag.bundler64) $(emo.bug)$(emo.fire): bug fixed in 65798c09a00662a3 has re-appeared'; exit 1; fi;
	@$(call b.call.patch-export-default,1,0,$(logtag.bundler64))
	@chmod -x $(out.bundler64.wasm)
	@$(call b.call.wasm-strip,bundler64)
	@$(call b.do.wasm-opt,bundler64)
	@$(call b.strip-js-emcc-bindings,$(logtag.bundler64))
	@echo '$(logtag.bundler64) $(emo.disk) s/"sqlite3-bundler-friendly-64bit.wasm"/"sqlite3-64bit.wasm"/g in $(dir.dout)/$(notdir $@)'; \
sed -e 's/"sqlite3-bundler-friendly-64bit.wasm"/"sqlite3-64bit.wasm"/g' -e "s/'sqlite3-bundler-friendly-64bit.wasm'/'sqlite3-64bit.wasm'/g" $@ > $(dir.dout)/$(notdir $@);
	@$(call b.echo,bundler64,$(emo.done) done!)

64bit: $(out.bundler64.js)
$(out.bundler64.wasm): $(out.bundler64.js)
b-bundler64: $(out.bundler64.wasm)
$(dir.dout)/sqlite3-bundler-friendly-64bit.mjs: $(out.bundler64.js)
more: $(out.bundler64.js)
# End build [bundler64]
########################################################################

########################################################################
# Begin build [🛼speedtest1]. flags=0xc0000000
# zCmppD=
# zBaseName=speedtest1
b.names += speedtest1
emo.b.speedtest1 = 🛼
logtag.speedtest1 ?= [$(emo.b.speedtest1)$(if $@, $@,)]:
$(info $(logtag.speedtest1) Setting up target b-speedtest1)
dir.dout.speedtest1 ?= $(dir.dout)/speedtest1
out.speedtest1.base ?= $(dir.dout.speedtest1)/speedtest1
out.speedtest1.js ?= $(dir.dout.speedtest1)/speedtest1.js
out.speedtest1.wasm ?= $(dir.dout.speedtest1)/speedtest1.wasm
dir.dout.speedtest1 ?= $(dir.dout)/speedtest1
c-pp.D.speedtest1 ?= 
emcc.environment.speedtest1 ?= web,worker
deps.speedtest1 += $(speedtest1.c.in) $(EXPORTED_FUNCTIONS.speedtest1)
sqlite3-api.speedtest1.js = $(dir.tmp)/sqlite3-api.speedtest1.js
$(eval $(call b.c-pp.target,speedtest1,$(sqlite3-api.jses),$(sqlite3-api.speedtest1.js),$(c-pp.D.speedtest1)))
$(out.speedtest1.js): $(sqlite3-api.speedtest1.js)
$(sqlite3-api.speedtest1.js): $(dir.api)/opfs-common-shared.c-pp.js $(dir.api)/opfs-common-inline.c-pp.js

########################################################################
# Begin --pre/--post flags for speedtest1
# --pre-js=...
pre-js.speedtest1.js = $(dir.tmp)/pre-js.speedtest1.js
$(pre-js.speedtest1.js): $(pre-js.in.js) $(bin.c-pp) $(MAKEFILE_LIST)
	@$(call b.mkdir@); $(call b.c-pp.shcmd,speedtest1,$(pre-js.in.js),$(pre-js.speedtest1.js),$(c-pp.D.speedtest1) -DModule.instantiateWasm )

# --post-js=...
post-js.speedtest1.js = $(dir.tmp)/post-js.speedtest1.js
post-js.speedtest1.in = $(dir.api)/post-js-header.js $(sqlite3-api.speedtest1.js) $(dir.api)/post-js-footer.js
$(eval $(call b.c-pp.target,speedtest1,$(post-js.speedtest1.in),$(post-js.speedtest1.js),$(c-pp.D.speedtest1)))
$(post-js.speedtest1.js): $(post-js.speedtest1.in) $(bin.c-pp)

# --extern-post-js=...
extern-post-js.speedtest1.js = $(dir.tmp)/extern-post-js.speedtest1.js
$(eval $(call b.c-pp.target,speedtest1,$(extern-post-js.in.js),$(extern-post-js.speedtest1.js),$(c-pp.D.speedtest1) --@policy=error -Dsqlite3.wasm=speedtest1.wasm))
# --pre/post misc...
pre-post.speedtest1.flags = --extern-pre-js=$(sqlite3-license-version.js) --pre-js=$(pre-js.speedtest1.js) --post-js=$(post-js.speedtest1.js) --extern-post-js=$(extern-post-js.speedtest1.js)
pre-post.speedtest1.deps = $(pre-post-jses.common.deps) $(post-js.speedtest1.js) $(extern-post-js.speedtest1.js) $(dir.tmp)/pre-js.speedtest1.js
# End --pre/--post flags for speedtest1
########################################################################

########################################################################
$(out.speedtest1.js): $(MAKEFILE_LIST) $(sqlite3-wasm.c.in) $(EXPORTED_FUNCTIONS.api) $(deps.speedtest1) $(bin.mkwb) $(pre-post.speedtest1.deps)
	@$(call b.mkdir@); $(call b.echo,speedtest1,$(emo.compile) building ...)
	$(b.cmd@)$(bin.emcc) -o $@ $(emcc.speedtest1) $(emcc.speedtest1.common) $(pre-post.speedtest1.flags) $(cflags.common) -DSQLITE_SPEEDTEST1_WASM $(SQLITE_OPT) -USQLITE_WASM_BARE_BONES -USQLITE_C -DSQLITE_C=$(sqlite3.c) $(speedtest1.exit-runtime0) $(speedtest1.c.in) -lm $(emcc.flags.speedtest1)
	@if grep -e '^ *importScripts(' $@; then echo '$(logtag.speedtest1) $(emo.bug)$(emo.fire): bug fixed in 65798c09a00662a3 has re-appeared'; exit 1; fi;
	@chmod -x $(out.speedtest1.wasm)
	@$(call b.call.wasm-strip,speedtest1)
	@$(call b.do.wasm-opt,speedtest1)
	@$(call b.strip-js-emcc-bindings,$(logtag.speedtest1))
	@$(call b.cp,speedtest1,$@,$(dir.dout))
	@$(call b.cp,speedtest1,$(basename $@).wasm,$(dir.dout))
	@$(call b.echo,speedtest1,$(emo.done) done!)

32bit: $(out.speedtest1.js)
$(out.speedtest1.wasm): $(out.speedtest1.js)
b-speedtest1: $(out.speedtest1.wasm)
$(dir.dout)/speedtest1.js: $(out.speedtest1.js)
$(dir.dout)/speedtest1.wasm: $(out.speedtest1.wasm)
all: $(out.speedtest1.js)
# End build [speedtest1]
########################################################################

########################################################################
# Begin build [🛼64speedtest164]. flags=0xc0000008
# zCmppD=
# zBaseName=speedtest1-64bit
b.names += speedtest164
emo.b.speedtest164 = 🛼64
logtag.speedtest164 ?= [$(emo.b.speedtest164)$(if $@, $@,)]:
$(info $(logtag.speedtest164) Setting up target b-speedtest164)
dir.dout.speedtest164 ?= $(dir.dout)/speedtest164
out.speedtest164.base ?= $(dir.dout.speedtest164)/speedtest1-64bit
out.speedtest164.js ?= $(dir.dout.speedtest164)/speedtest1-64bit.js
out.speedtest164.wasm ?= $(dir.dout.speedtest164)/speedtest1-64bit.wasm
dir.dout.speedtest164 ?= $(dir.dout)/speedtest164
c-pp.D.speedtest164 ?= 
emcc.environment.speedtest164 ?= web,worker
deps.speedtest164 += $(speedtest1.c.in) $(EXPORTED_FUNCTIONS.speedtest1)
sqlite3-api.speedtest164.js = $(dir.tmp)/sqlite3-api.speedtest164.js
$(eval $(call b.c-pp.target,speedtest164,$(sqlite3-api.jses),$(sqlite3-api.speedtest164.js),$(c-pp.D.speedtest164)))
$(out.speedtest164.js): $(sqlite3-api.speedtest164.js)
$(sqlite3-api.speedtest164.js): $(dir.api)/opfs-common-shared.c-pp.js $(dir.api)/opfs-common-inline.c-pp.js

########################################################################
# Begin --pre/--post flags for speedtest164
# --pre-js=...
pre-js.speedtest164.js = $(dir.tmp)/pre-js.speedtest164.js
$(pre-js.speedtest164.js): $(pre-js.in.js) $(bin.c-pp) $(MAKEFILE_LIST)
	@$(call b.mkdir@); $(call b.c-pp.shcmd,speedtest164,$(pre-js.in.js),$(pre-js.speedtest164.js),$(c-pp.D.speedtest164) -DModule.instantiateWasm )

# --post-js=...
post-js.speedtest164.js = $(dir.tmp)/post-js.speedtest164.js
post-js.speedtest164.in = $(dir.api)/post-js-header.js $(sqlite3-api.speedtest164.js) $(dir.api)/post-js-footer.js
$(eval $(call b.c-pp.target,speedtest164,$(post-js.speedtest164.in),$(post-js.speedtest164.js),$(c-pp.D.speedtest164)))
$(post-js.speedtest164.js): $(post-js.speedtest164.in) $(bin.c-pp)

# --extern-post-js=...
extern-post-js.speedtest164.js = $(dir.tmp)/extern-post-js.speedtest164.js
$(eval $(call b.c-pp.target,speedtest164,$(extern-post-js.in.js),$(extern-post-js.speedtest164.js),$(c-pp.D.speedtest164) --@policy=error -Dsqlite3.wasm=speedtest1-64bit.wasm))
# --pre/post misc...
pre-post.speedtest164.flags = --extern-pre-js=$(sqlite3-license-version.js) --pre-js=$(pre-js.speedtest164.js) --post-js=$(post-js.speedtest164.js) --extern-post-js=$(extern-post-js.speedtest164.js)
pre-post.speedtest164.deps = $(pre-post-jses.common.deps) $(post-js.speedtest164.js) $(extern-post-js.speedtest164.js) $(dir.tmp)/pre-js.speedtest164.js
# End --pre/--post flags for speedtest164
########################################################################

########################################################################
$(out.speedtest164.js): $(MAKEFILE_LIST) $(sqlite3-wasm.c.in) $(EXPORTED_FUNCTIONS.api) $(deps.speedtest164) $(bin.mkwb) $(pre-post.speedtest164.deps)
	@$(call b.mkdir@); $(call b.echo,speedtest164,$(emo.compile) building ...)
	$(b.cmd@)$(bin.emcc) -o $@ $(emcc.speedtest1) $(emcc.speedtest1.common) -sMEMORY64=1 -sWASM_BIGINT=1 $(pre-post.speedtest164.flags) $(cflags.common) -DSQLITE_SPEEDTEST1_WASM $(SQLITE_OPT) -USQLITE_WASM_BARE_BONES -USQLITE_C -DSQLITE_C=$(sqlite3.c) $(speedtest1.exit-runtime0) $(speedtest1.c.in) -lm $(emcc.flags.speedtest164)
	@if grep -e '^ *importScripts(' $@; then echo '$(logtag.speedtest164) $(emo.bug)$(emo.fire): bug fixed in 65798c09a00662a3 has re-appeared'; exit 1; fi;
	@chmod -x $(out.speedtest164.wasm)
	@$(call b.call.wasm-strip,speedtest164)
	@$(call b.do.wasm-opt,speedtest164)
	@$(call b.strip-js-emcc-bindings,$(logtag.speedtest164))
	@$(call b.cp,speedtest164,$@,$(dir.dout))
	@$(call b.cp,speedtest164,$(basename $@).wasm,$(dir.dout))
	@$(call b.echo,speedtest164,$(emo.done) done!)

32bit: $(out.speedtest164.js)
$(out.speedtest164.wasm): $(out.speedtest164.js)
b-speedtest164: $(out.speedtest164.wasm)
$(dir.dout)/speedtest1-64bit.js: $(out.speedtest164.js)
$(dir.dout)/speedtest1-64bit.wasm: $(out.speedtest164.wasm)
more: $(out.speedtest164.js)
# End build [speedtest164]
########################################################################

########################################################################
# Begin build [🍟node]. flags=0x40000025
# zCmppD=-Dtarget:node $(c-pp.D.bundler)
# zBaseName=sqlite3-node
b.names += node
emo.b.node = 🍟
logtag.node ?= [$(emo.b.node)$(if $@, $@,)]:
$(info $(logtag.node) Setting up target b-node)
dir.dout.node ?= $(dir.dout)/node
out.node.base ?= $(dir.dout.node)/sqlite3-node
out.node.js ?= $(dir.dout.node)/sqlite3-node.mjs
out.node.wasm ?= $(dir.dout.node)/sqlite3-node.wasm
dir.dout.node ?= $(dir.dout)/node
c-pp.D.node ?= -Dtarget:node $(c-pp.D.bundler)
c-pp.D.node += -Dunsupported-build
emcc.environment.node ?= node
sqlite3-api.node.js = $(dir.tmp)/sqlite3-api.node.js
$(eval $(call b.c-pp.target,node,$(sqlite3-api.jses),$(sqlite3-api.node.js),$(c-pp.D.node)))
$(out.node.js): $(sqlite3-api.node.js)
$(sqlite3-api.node.js): $(dir.api)/opfs-common-shared.c-pp.js $(dir.api)/opfs-common-inline.c-pp.js

########################################################################
# Begin --pre/--post flags for node
# --pre-js=...
pre-js.node.js = $(dir.tmp)/pre-js.node.js
$(pre-js.node.js): $(pre-js.in.js) $(bin.c-pp) $(MAKEFILE_LIST) $(dir.dout)/sqlite3.wasm
	@$(call b.mkdir@); $(call b.c-pp.shcmd,node,$(pre-js.in.js),$(pre-js.node.js),$(c-pp.D.node) -DModule.instantiateWasm )

# --post-js=...
post-js.node.js = $(dir.tmp)/post-js.node.js
post-js.node.in = $(dir.api)/post-js-header.js $(sqlite3-api.node.js) $(dir.api)/post-js-footer.js
$(eval $(call b.c-pp.target,node,$(post-js.node.in),$(post-js.node.js),$(c-pp.D.node)))
$(post-js.node.js): $(post-js.node.in) $(bin.c-pp)

# --extern-post-js=...
extern-post-js.node.js = $(dir.tmp)/extern-post-js.node.js
$(eval $(call b.c-pp.target,node,$(extern-post-js.in.js),$(extern-post-js.node.js),$(c-pp.D.node) --@policy=error -Dsqlite3.wasm=sqlite3-node.wasm))
# --pre/post misc...
pre-post.node.flags = --extern-pre-js=$(sqlite3-license-version.js) --pre-js=$(pre-js.node.js) --post-js=$(post-js.node.js) --extern-post-js=$(extern-post-js.node.js)
pre-post.node.deps = $(pre-post-jses.common.deps) $(post-js.node.js) $(extern-post-js.node.js) $(dir.tmp)/pre-js.node.js
# End --pre/--post flags for node
########################################################################

########################################################################
$(out.node.js): $(MAKEFILE_LIST) $(sqlite3-wasm.c.in) $(EXPORTED_FUNCTIONS.api) $(deps.node) $(bin.mkwb) $(pre-post.node.deps)
	@$(call b.mkdir@); $(call b.echo,node,$(emo.compile) building ...)
	@echo '$(logtag.node) $(label.unsupported-build)'
	$(b.cmd@)$(bin.emcc) -o $@ $(emcc_opt_full) $(emcc.flags) $(emcc.jsflags) -sENVIRONMENT=$(emcc.environment.node) $(pre-post.node.flags) $(emcc.flags.node) $(cflags.common) $(cflags.node) $(SQLITE_OPT) $(cflags.wasm_extra_init) $(sqlite3-wasm.c.in)
	@if grep -e '^ *importScripts(' $@; then echo '$(logtag.node) $(emo.bug)$(emo.fire): bug fixed in 65798c09a00662a3 has re-appeared'; exit 1; fi;
	@$(call b.call.patch-export-default,1,0,$(logtag.node))
	@chmod -x $(out.node.wasm)
	@$(call b.call.wasm-strip,node)
	@$(call b.do.wasm-opt,node)
	@$(call b.strip-js-emcc-bindings,$(logtag.node))
	@echo '$(logtag.node) $(emo.disk) s/"sqlite3-node.wasm"/"sqlite3.wasm"/g in $(dir.dout)/$(notdir $@)'; \
sed -e 's/"sqlite3-node.wasm"/"sqlite3.wasm"/g' -e "s/'sqlite3-node.wasm'/'sqlite3.wasm'/g" $@ > $(dir.dout)/$(notdir $@);
	@$(call b.echo,node,$(emo.done) done! $(label.unsupported-build))

32bit: $(out.node.js)
$(out.node.wasm): $(out.node.js)
b-node: $(out.node.wasm)
$(dir.dout)/sqlite3-node.mjs: $(out.node.js)
more: $(out.node.js)
# End build [node]
########################################################################

########################################################################
# Begin build [🍔node64]. flags=0x40000035
# zCmppD=-Dtarget:node $(c-pp.D.bundler)
# zBaseName=sqlite3-node-64bit
b.names += node64
emo.b.node64 = 🍔
logtag.node64 ?= [$(emo.b.node64)$(if $@, $@,)]:
$(info $(logtag.node64) Setting up target b-node64)
dir.dout.node64 ?= $(dir.dout)/node64
out.node64.base ?= $(dir.dout.node64)/sqlite3-node-64bit
out.node64.js ?= $(dir.dout.node64)/sqlite3-node-64bit.mjs
out.node64.wasm ?= $(dir.dout.node64)/sqlite3-node-64bit.wasm
dir.dout.node64 ?= $(dir.dout)/node64
c-pp.D.node64 ?= -Dtarget:node $(c-pp.D.bundler)
c-pp.D.node64 += $(c-pp.D.64bit)
c-pp.D.node64 += -Dunsupported-build
emcc.environment.node64 ?= node
sqlite3-api.node64.js = $(dir.tmp)/sqlite3-api.node64.js
$(eval $(call b.c-pp.target,node64,$(sqlite3-api.jses),$(sqlite3-api.node64.js),$(c-pp.D.node64)))
$(out.node64.js): $(sqlite3-api.node64.js)
$(sqlite3-api.node64.js): $(dir.api)/opfs-common-shared.c-pp.js $(dir.api)/opfs-common-inline.c-pp.js

########################################################################
# Begin --pre/--post flags for node64
# --pre-js=...
pre-js.node64.js = $(dir.tmp)/pre-js.node64.js
$(pre-js.node64.js): $(pre-js.in.js) $(bin.c-pp) $(MAKEFILE_LIST) $(dir.dout)/sqlite3-64bit.wasm
	@$(call b.mkdir@); $(call b.c-pp.shcmd,node64,$(pre-js.in.js),$(pre-js.node64.js),$(c-pp.D.node64) -DModule.instantiateWasm )

# --post-js=...
post-js.node64.js = $(dir.tmp)/post-js.node64.js
post-js.node64.in = $(dir.api)/post-js-header.js $(sqlite3-api.node64.js) $(dir.api)/post-js-footer.js
$(eval $(call b.c-pp.target,node64,$(post-js.node64.in),$(post-js.node64.js),$(c-pp.D.node64)))
$(post-js.node64.js): $(post-js.node64.in) $(bin.c-pp)

# --extern-post-js=...
extern-post-js.node64.js = $(dir.tmp)/extern-post-js.node64.js
$(eval $(call b.c-pp.target,node64,$(extern-post-js.in.js),$(extern-post-js.node64.js),$(c-pp.D.node64) --@policy=error -Dsqlite3.wasm=sqlite3-node-64bit.wasm))
# --pre/post misc...
pre-post.node64.flags = --extern-pre-js=$(sqlite3-license-version.js) --pre-js=$(pre-js.node64.js) --post-js=$(post-js.node64.js) --extern-post-js=$(extern-post-js.node64.js)
pre-post.node64.deps = $(pre-post-jses.common.deps) $(post-js.node64.js) $(extern-post-js.node64.js) $(dir.tmp)/pre-js.node64.js
# End --pre/--post flags for node64
########################################################################

########################################################################
$(out.node64.js): $(MAKEFILE_LIST) $(sqlite3-wasm.c.in) $(EXPORTED_FUNCTIONS.api) $(deps.node64) $(bin.mkwb) $(pre-post.node64.deps)
	@$(call b.mkdir@); $(call b.echo,node64,$(emo.compile) building ...)
	@echo '$(logtag.node64) $(label.unsupported-build)'
	$(b.cmd@)$(bin.emcc) -o $@ $(emcc_opt_full) $(emcc.flags) $(emcc.jsflags) -sENVIRONMENT=$(emcc.environment.node64) $(pre-post.node64.flags) $(emcc.flags.node64) $(cflags.common) $(cflags.node64) $(SQLITE_OPT) $(cflags.wasm_extra_init) $(sqlite3-wasm.c.in)
	@if grep -e '^ *importScripts(' $@; then echo '$(logtag.node64) $(emo.bug)$(emo.fire): bug fixed in 65798c09a00662a3 has re-appeared'; exit 1; fi;
	@$(call b.call.patch-export-default,1,0,$(logtag.node64))
	@chmod -x $(out.node64.wasm)
	@$(call b.call.wasm-strip,node64)
	@$(call b.do.wasm-opt,node64)
	@$(call b.strip-js-emcc-bindings,$(logtag.node64))
	@echo '$(logtag.node64) $(emo.disk) s/"sqlite3-node-64bit.wasm"/"sqlite3-64bit.wasm"/g in $(dir.dout)/$(notdir $@)'; \
sed -e 's/"sqlite3-node-64bit.wasm"/"sqlite3-64bit.wasm"/g' -e "s/'sqlite3-node-64bit.wasm'/'sqlite3-64bit.wasm'/g" $@ > $(dir.dout)/$(notdir $@);
	@$(call b.echo,node64,$(emo.done) done! $(label.unsupported-build))

64bit: $(out.node64.js)
$(out.node64.wasm): $(out.node64.js)
b-node64: $(out.node64.wasm)
$(dir.dout)/sqlite3-node-64bit.mjs: $(out.node64.js)
more: $(out.node64.js)
# End build [node64]
########################################################################

########################################################################
# Begin build [💿wasmfs]. flags=0xc0000045
# zCmppD=$(c-pp.D.bundler) -Dwasmfs
# zBaseName=sqlite3-wasmfs
b.names += wasmfs
emo.b.wasmfs = 💿
logtag.wasmfs ?= [$(emo.b.wasmfs)$(if $@, $@,)]:
$(info $(logtag.wasmfs) Setting up target b-wasmfs)
ifeq (1,$(wasmfs.enable))
dir.dout.wasmfs ?= $(dir.dout)/wasmfs
out.wasmfs.base ?= $(dir.dout.wasmfs)/sqlite3-wasmfs
out.wasmfs.js ?= $(dir.dout.wasmfs)/sqlite3-wasmfs.mjs
out.wasmfs.wasm ?= $(dir.dout.wasmfs)/sqlite3-wasmfs.wasm
dir.dout.wasmfs ?= $(dir.dout)/wasmfs
c-pp.D.wasmfs ?= $(c-pp.D.bundler) -Dwasmfs
c-pp.D.wasmfs += -Dunsupported-build
emcc.environment.wasmfs ?= web,worker
emcc.flags.wasmfs = -sEXPORT_ES6 -sUSE_ES6_IMPORT_META -sUSE_CLOSURE_COMPILER=0 -pthread -sWASMFS -sPTHREAD_POOL_SIZE=1 -sERROR_ON_UNDEFINED_SYMBOLS=0 -sLLD_REPORT_UNDEFINED -DSQLITE_ENABLE_WASMFS
sqlite3-api.wasmfs.js = $(dir.tmp)/sqlite3-api.wasmfs.js
$(eval $(call b.c-pp.target,wasmfs,$(sqlite3-api.jses),$(sqlite3-api.wasmfs.js),$(c-pp.D.wasmfs)))
$(out.wasmfs.js): $(sqlite3-api.wasmfs.js)
$(sqlite3-api.wasmfs.js): $(dir.api)/opfs-common-shared.c-pp.js $(dir.api)/opfs-common-inline.c-pp.js

########################################################################
# Begin --pre/--post flags for wasmfs
# --pre-js=...
pre-js.wasmfs.js = $(dir.tmp)/pre-js.wasmfs.js
$(pre-js.wasmfs.js): $(pre-js.in.js) $(bin.c-pp) $(MAKEFILE_LIST)
	@$(call b.mkdir@); $(call b.c-pp.shcmd,wasmfs,$(pre-js.in.js),$(pre-js.wasmfs.js),$(c-pp.D.wasmfs) -DModule.instantiateWasm )

# --post-js=...
post-js.wasmfs.js = $(dir.tmp)/post-js.wasmfs.js
post-js.wasmfs.in = $(dir.api)/post-js-header.js $(sqlite3-api.wasmfs.js) $(dir.api)/post-js-footer.js
$(eval $(call b.c-pp.target,wasmfs,$(post-js.wasmfs.in),$(post-js.wasmfs.js),$(c-pp.D.wasmfs)))
$(post-js.wasmfs.js): $(post-js.wasmfs.in) $(bin.c-pp)

# --extern-post-js=...
extern-post-js.wasmfs.js = $(dir.tmp)/extern-post-js.wasmfs.js
$(eval $(call b.c-pp.target,wasmfs,$(extern-post-js.in.js),$(extern-post-js.wasmfs.js),$(c-pp.D.wasmfs) --@policy=error -Dsqlite3.wasm=sqlite3-wasmfs.wasm))
# --pre/post misc...
pre-post.wasmfs.flags = --extern-pre-js=$(sqlite3-license-version.js) --pre-js=$(pre-js.wasmfs.js) --post-js=$(post-js.wasmfs.js) --extern-post-js=$(extern-post-js.wasmfs.js)
pre-post.wasmfs.deps = $(pre-post-jses.common.deps) $(post-js.wasmfs.js) $(extern-post-js.wasmfs.js) $(dir.tmp)/pre-js.wasmfs.js
# End --pre/--post flags for wasmfs
########################################################################

########################################################################
$(out.wasmfs.js): $(MAKEFILE_LIST) $(sqlite3-wasm.c.in) $(EXPORTED_FUNCTIONS.api) $(deps.wasmfs) $(bin.mkwb) $(pre-post.wasmfs.deps)
	@$(call b.mkdir@); $(call b.echo,wasmfs,$(emo.compile) building ...)
	@echo '$(logtag.wasmfs) $(label.unsupported-build)'
	$(b.cmd@)$(bin.emcc) -o $@ $(emcc_opt_full) $(emcc.flags) $(emcc.jsflags) -sENVIRONMENT=$(emcc.environment.wasmfs) $(pre-post.wasmfs.flags) $(emcc.flags.wasmfs) $(cflags.common) $(cflags.wasmfs) $(SQLITE_OPT) $(cflags.wasm_extra_init) $(sqlite3-wasm.c.in)
	@if grep -e '^ *importScripts(' $@; then echo '$(logtag.wasmfs) $(emo.bug)$(emo.fire): bug fixed in 65798c09a00662a3 has re-appeared'; exit 1; fi;
	@$(call b.call.patch-export-default,1,1,$(logtag.wasmfs))
	@chmod -x $(out.wasmfs.wasm)
	@$(call b.call.wasm-strip,wasmfs)
	@$(call b.do.wasm-opt,wasmfs)
	@$(call b.strip-js-emcc-bindings,$(logtag.wasmfs))
	@$(call b.cp,wasmfs,$@,$(dir.dout))
	@$(call b.cp,wasmfs,$(basename $@).wasm,$(dir.dout))
	@$(call b.echo,wasmfs,$(emo.done) done! $(label.unsupported-build))

32bit: $(out.wasmfs.js)
$(out.wasmfs.wasm): $(out.wasmfs.js)
b-wasmfs: $(out.wasmfs.wasm)
$(dir.dout)/sqlite3-wasmfs.mjs: $(out.wasmfs.js)
$(dir.dout)/sqlite3-wasmfs.wasm: $(out.wasmfs.wasm)
more: $(out.wasmfs.js)
else
$(info $(logtag.wasmfs) $(emo.stop) disabled by condition: ifeq (1,$(wasmfs.enable)))
endif
# End build [wasmfs]
########################################################################

########################################################################
# Begin build fiddle
emo.b.fiddle = 🎻
logtag.fiddle ?= [$(emo.b.fiddle)$(if $@, $@,)]:
$(info $(logtag.fiddle) Setting up target b-fiddle)
dir.fiddle = fiddle
out.fiddle.js = $(dir.fiddle)/fiddle-module.js
out.fiddle.wasm = $(dir.fiddle)/fiddle-module.wasm
$(out.fiddle.wasm): $(out.fiddle.js)
sqlite3-api.fiddle.js = $(dir.tmp)/sqlite3-api.fiddle.js
$(eval $(call b.c-pp.target,fiddle,$(sqlite3-api.jses),$(sqlite3-api.fiddle.js),$(c-pp.D.fiddle)))
$(out.fiddle.js): $(sqlite3-api.fiddle.js)
$(sqlite3-api.fiddle.js): $(dir.api)/opfs-common-shared.c-pp.js $(dir.api)/opfs-common-inline.c-pp.js

########################################################################
# Begin --pre/--post flags for fiddle
# --pre-js=...
pre-js.fiddle.js = $(dir.tmp)/pre-js.fiddle.js
$(eval $(call b.c-pp.target,fiddle,$(pre-js.in.js),$(pre-js.fiddle.js),$(c-pp.D.fiddle)))
# --post-js=...
post-js.fiddle.js = $(dir.tmp)/post-js.fiddle.js
post-js.fiddle.in = $(dir.api)/post-js-header.js $(sqlite3-api.fiddle.js) $(dir.api)/post-js-footer.js
$(eval $(call b.c-pp.target,fiddle,$(post-js.fiddle.in),$(post-js.fiddle.js),$(c-pp.D.fiddle)))
$(post-js.fiddle.js): $(post-js.fiddle.in) $(bin.c-pp)

# --extern-post-js=...
extern-post-js.fiddle.js = $(dir.tmp)/extern-post-js.fiddle.js
$(eval $(call b.c-pp.target,fiddle,$(extern-post-js.in.js),$(extern-post-js.fiddle.js),$(c-pp.D.fiddle)))
# --pre/post misc...
pre-post.fiddle.flags = --extern-pre-js=$(sqlite3-license-version.js) --pre-js=$(pre-js.fiddle.js) --post-js=$(post-js.fiddle.js) --extern-post-js=$(extern-post-js.fiddle.js)
pre-post.fiddle.deps = $(pre-post-jses.common.deps) $(post-js.fiddle.js) $(extern-post-js.fiddle.js) $(dir.tmp)/pre-js.fiddle.js
# End --pre/--post flags for fiddle
########################################################################
$(out.fiddle.js): $(MAKEFILE_LIST) $(EXPORTED_FUNCTIONS.fiddle) $(fiddle.c.in) $(pre-post.fiddle.deps) $(dir.dout)/sqlite3-opfs-async-proxy.js
	@$(call b.mkdir@); $(call b.echo,fiddle,$(emo.compile) building ...)
	@$(call b.mkdir@)
	$(b.cmd@)$(bin.emcc) -o $@ $(emcc.flags.fiddle) $(pre-post.fiddle.flags) $(fiddle.c.in)
	@chmod -x $(out.fiddle.wasm)
	@$(call b.call.wasm-strip,fiddle)
	@$(call b.strip-js-emcc-bindings,$(logtag.fiddle))
	@$(call b.cp,fiddle,$(dir.dout)/sqlite3-opfs-async-proxy.js,$(dir $@))
	@$(call b.echo,fiddle,$(emo.done) done!)

all: $(out.fiddle.wasm)

$(out.fiddle.js).gz: $(out.fiddle.js)
	@$(call b.echo,fiddle,$(emo.disk))
	@gzip < $< > $@

$(out.fiddle.wasm).gz: $(out.fiddle.wasm)
	@$(call b.echo,fiddle,$(emo.disk))
	@gzip < $< > $@

fiddle: $(out.fiddle.js).gz $(out.fiddle.wasm).gz
b-fiddle: fiddle
all: b-fiddle
# End fiddle
########################################################################

########################################################################
# Begin build fiddle.debug
emo.b.fiddle.debug = $(emo.b.fiddle)$(emo.bug)
logtag.fiddle.debug ?= [$(emo.b.fiddle.debug)$(if $@, $@,)]:
$(info $(logtag.fiddle.debug) Setting up target b-fiddle.debug)
dir.fiddle.debug = fiddle.debug
out.fiddle.debug.js = $(dir.fiddle.debug)/fiddle-module.js
out.fiddle.debug.wasm = $(dir.fiddle.debug)/fiddle-module.wasm
$(out.fiddle.debug.wasm): $(out.fiddle.debug.js)
sqlite3-api.fiddle.debug.js = $(dir.tmp)/sqlite3-api.fiddle.debug.js
$(eval $(call b.c-pp.target,fiddle.debug,$(sqlite3-api.jses),$(sqlite3-api.fiddle.debug.js),$(c-pp.D.fiddle.debug)))
$(out.fiddle.debug.js): $(sqlite3-api.fiddle.debug.js)
$(sqlite3-api.fiddle.debug.js): $(dir.api)/opfs-common-shared.c-pp.js $(dir.api)/opfs-common-inline.c-pp.js

########################################################################
# Begin --pre/--post flags for fiddle.debug
# --pre-js=...
pre-js.fiddle.debug.js = $(dir.tmp)/pre-js.fiddle.debug.js
$(eval $(call b.c-pp.target,fiddle.debug,$(pre-js.in.js),$(pre-js.fiddle.debug.js),$(c-pp.D.fiddle.debug)))
# --post-js=...
post-js.fiddle.debug.js = $(dir.tmp)/post-js.fiddle.debug.js
post-js.fiddle.debug.in = $(dir.api)/post-js-header.js $(sqlite3-api.fiddle.debug.js) $(dir.api)/post-js-footer.js
$(eval $(call b.c-pp.target,fiddle.debug,$(post-js.fiddle.debug.in),$(post-js.fiddle.debug.js),$(c-pp.D.fiddle.debug)))
$(post-js.fiddle.debug.js): $(post-js.fiddle.debug.in) $(bin.c-pp)

# --extern-post-js=...
extern-post-js.fiddle.debug.js = $(dir.tmp)/extern-post-js.fiddle.debug.js
$(eval $(call b.c-pp.target,fiddle.debug,$(extern-post-js.in.js),$(extern-post-js.fiddle.debug.js),$(c-pp.D.fiddle.debug)))
# --pre/post misc...
pre-post.fiddle.debug.flags = --extern-pre-js=$(sqlite3-license-version.js) --pre-js=$(pre-js.fiddle.debug.js) --post-js=$(post-js.fiddle.debug.js) --extern-post-js=$(extern-post-js.fiddle.debug.js)
pre-post.fiddle.debug.deps = $(pre-post-jses.common.deps) $(post-js.fiddle.debug.js) $(extern-post-js.fiddle.debug.js) $(dir.tmp)/pre-js.fiddle.debug.js
# End --pre/--post flags for fiddle.debug
########################################################################
$(out.fiddle.debug.js): $(MAKEFILE_LIST) $(EXPORTED_FUNCTIONS.fiddle) $(fiddle.c.in) $(pre-post.fiddle.debug.deps) $(dir.dout)/sqlite3-opfs-async-proxy.js $(dir.fiddle)/fiddle-worker.js $(dir.fiddle)/fiddle.js $(dir.fiddle)/index.html
	@$(call b.mkdir@); $(call b.echo,fiddle.debug,$(emo.compile) building ...)
	@$(call b.mkdir@)
	$(b.cmd@)$(bin.emcc) -o $@ $(emcc.flags.fiddle.debug) $(pre-post.fiddle.debug.flags) $(fiddle.c.in)
	@chmod -x $(out.fiddle.debug.wasm)
	@$(call b.call.wasm-strip,fiddle.debug)
	@$(call b.strip-js-emcc-bindings,$(logtag.fiddle.debug))
	@$(call b.cp,fiddle.debug,$(dir.dout)/sqlite3-opfs-async-proxy.js,$(dir $@))
	@$(call b.cp,fiddle.debug,$(dir.fiddle)/index.html $(dir.fiddle)/fiddle.js $(dir.fiddle)/fiddle-worker.js $(dir $@))
	@$(call b.echo,fiddle.debug,$(emo.done) done!)

more: $(out.fiddle.debug.wasm)

$(out.fiddle.debug.js).gz: $(out.fiddle.debug.js)
	@$(call b.echo,fiddle.debug,$(emo.disk))
	@gzip < $< > $@

$(out.fiddle.debug.wasm).gz: $(out.fiddle.debug.wasm)
	@$(call b.echo,fiddle.debug,$(emo.disk))
	@gzip < $< > $@

fiddle.debug: $(out.fiddle.debug.js).gz $(out.fiddle.debug.wasm).gz
b-fiddle.debug: fiddle.debug
fiddle-debug: fiddle.debug
# End fiddle.debug
########################################################################
